package sieg

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/shirou/gopsutil/v3/disk"
)

// runBackupCmd is the top-level dispatcher for `simplesiem backup …`.
// Falls through to the local-host backup path unless one of the
// remote-mode flags (--agent / --realm / --all) is set, which routes
// to the server / master orchestrator instead.
func runBackupCmd(args []string) {
	if len(args) > 0 && args[0] == "inspect" {
		runBackupInspect(args[1:])
		return
	}
	if len(args) > 0 && args[0] == "verify" {
		runBackupVerify(args[1:])
		return
	}
	// Peek for remote-mode flags so we can split into the right
	// codepath without parsing the full flag set twice. None set →
	// local-only backup.
	hasRemoteFlag := false
	for _, a := range args {
		switch a {
		case "--agent", "--realm", "--all", "-agent", "-realm", "-all":
			hasRemoteFlag = true
		}
		if strings.HasPrefix(a, "--agent=") || strings.HasPrefix(a, "--realm=") {
			hasRemoteFlag = true
		}
	}
	if hasRemoteFlag {
		runBackupRemote(args)
		return
	}
	runBackupLocal(args)
}

// runBackupLocal handles `simplesiem backup --out <path>` on whatever
// host the binary is currently running on. The daemon (if any) keeps
// running; the warning is printed before the work starts.
func runBackupLocal(args []string) {
	fs := flag.NewFlagSet("backup", flag.ExitOnError)
	cfgPath := fs.String("config", defaultConfigPath(), "config file")
	out := fs.String("out", "", "output backup file path; default: ./<auto-generated>.siembak")
	pass := fs.String("passphrase", "", "encryption passphrase (insecure on shell history; prefer --passphrase-file)")
	passFile := fs.String("passphrase-file", "", "path to a file holding the encryption passphrase (trimmed of trailing whitespace)")
	noEncrypt := fs.Bool("no-encrypt", false, "produce an unencrypted backup (NOT recommended; certs and PSKs land in plaintext)")
	noCompress := fs.Bool("no-compress", false, "skip gzip compression (faster, much larger file)")
	yes := fs.Bool("y", false, "skip the 'logs collected during backup will not be included' confirmation")
	_ = fs.Parse(args)

	cfg := loadConfig(*cfgPath)
	if *out == "" {
		*out = defaultBackupFilename(cfg)
	}
	passphrase, err := resolveBackupPassphrase(*pass, *passFile, *noEncrypt)
	if err != nil {
		fatalf("%v", err)
	}

	// Collector-mode constraint: refuse to write the backup file onto
	// the same volume that holds the log directory. The user
	// explicitly asked for this — the rationale is that a collector is
	// often paired with a higher authority that pulls the corpus, and
	// writing a multi-GB backup onto the same volume defeats the
	// "different storage partition" guarantee they want.
	if normaliseMode(cfg.Mode) == "collector" {
		if same, err := pathsOnSameVolume(*out, cfg.LogDir); err == nil && same {
			fatalf("collector mode: --out (%s) is on the same volume as log_dir (%s); pick a different storage partition for the backup",
				*out, cfg.LogDir)
		}
	}

	if !*yes {
		fmt.Fprintln(os.Stderr, "WARNING: events written to disk after this moment will NOT be in the backup.")
		fmt.Fprintln(os.Stderr, "         The daemon stays running during the backup, so collection continues normally.")
		fmt.Fprint(os.Stderr, "Continue? [y/N] ")
		var resp string
		_, _ = fmt.Scanln(&resp)
		resp = strings.TrimSpace(resp)
		if !strings.EqualFold(resp, "y") && !strings.EqualFold(resp, "yes") {
			fmt.Fprintln(os.Stderr, "aborted")
			os.Exit(1)
		}
	}

	if err := createBackup(cfg, *cfgPath, *out, passphrase, !*noCompress); err != nil {
		fatalf("backup: %v", err)
	}
	fi, _ := os.Stat(*out)
	size := int64(0)
	if fi != nil {
		size = fi.Size()
	}
	fmt.Printf("backup complete: %s (%s)\n", *out, formatBytesDecimal(uint64(size)))
	if passphrase == "" {
		fmt.Fprintln(os.Stderr, "WARNING: this backup is UNENCRYPTED. It contains private keys and PSKs in plaintext.")
	}
}

func runBackupInspect(args []string) {
	fs := flag.NewFlagSet("backup inspect", flag.ExitOnError)
	in := fs.String("in", "", "backup file path")
	pass := fs.String("passphrase", "", "passphrase if the backup is encrypted")
	passFile := fs.String("passphrase-file", "", "path to a file holding the passphrase")
	_ = fs.Parse(args)
	if *in == "" {
		fatalf("--in is required")
	}
	passphrase := *pass
	if *passFile != "" {
		b, err := os.ReadFile(*passFile)
		if err != nil {
			fatalf("read passphrase file: %v", err)
		}
		passphrase = strings.TrimSpace(string(b))
	}
	m, err := inspectBackup(*in, passphrase)
	if err != nil {
		fatalf("inspect: %v", err)
	}
	fmt.Printf("magic:        %s\n", m.Magic)
	fmt.Printf("version:      %d\n", m.Version)
	fmt.Printf("host_id:      %s\n", m.HostID)
	fmt.Printf("mode:         %s\n", m.Mode)
	if m.Realm != "" {
		fmt.Printf("realm:        %s\n", m.Realm)
	}
	fmt.Printf("created (UTC): %s\n", m.CreatedAtUTC.Format("2006-01-02 15:04:05"))
	fmt.Printf("created (local): %s %s\n", displayTS(m.CreatedAtUTC).Format("2006-01-02 15:04:05"), displayTZ())
	fmt.Printf("platform:     %s/%s\n", m.Platform, m.Arch)
	fmt.Printf("simplesiem:   %s (build %s)\n", m.SIEMVersion, m.SIEMBuild)
	fmt.Printf("encrypted:    %v\n", m.Encrypted)
	fmt.Printf("compressed:   %v\n", m.Compressed)
	fmt.Printf("config_dir:   %s\n", m.ConfigDir)
	fmt.Printf("state_dir:    %s\n", m.StateDir)
	fmt.Printf("log_dir:      %s\n", m.LogDir)
	if m.Note != "" {
		fmt.Printf("note:         %s\n", m.Note)
	}
}

// runRestoreCmd is the CLI entry point for `simplesiem restore`.
func runRestoreCmd(args []string) {
	fs := flag.NewFlagSet("restore", flag.ExitOnError)
	in := fs.String("in", "", "backup file path (required)")
	pass := fs.String("passphrase", "", "passphrase if the backup is encrypted")
	passFile := fs.String("passphrase-file", "", "path to a file holding the passphrase")
	dryRun := fs.Bool("dry-run", false, "print what would be restored without touching disk")
	cfgDir := fs.String("config-dir", "", "override: write config tree here instead of the manifest path")
	stateDir := fs.String("state-dir", "", "override: write state tree here instead of the manifest path")
	logDir := fs.String("log-dir", "", "override: write logs tree here instead of the manifest path")
	force := fs.Bool("force", false, "override the existing-install guard (allow restore over server/agent/master/collector)")
	yes := fs.Bool("y", false, "skip the destructive-restore confirmation prompt")
	_ = fs.Parse(args)

	if *in == "" {
		fatalf("--in is required")
	}
	passphrase := *pass
	if *passFile != "" {
		b, err := os.ReadFile(*passFile)
		if err != nil {
			fatalf("read passphrase file: %v", err)
		}
		passphrase = strings.TrimSpace(string(b))
	}
	if !*dryRun && !*yes {
		fmt.Fprintln(os.Stderr, "WARNING: restore overwrites config_dir, state_dir, and log_dir from the backup manifest.")
		fmt.Fprintln(os.Stderr, "         Existing trees are renamed to '<dir>.pre-restore-<random>' for manual rollback.")
		fmt.Fprintln(os.Stderr, "         The daemon should be stopped first: `simplesiem stop`.")
		fmt.Fprint(os.Stderr, "Continue? [y/N] ")
		var resp string
		_, _ = fmt.Scanln(&resp)
		resp = strings.TrimSpace(resp)
		if !strings.EqualFold(resp, "y") && !strings.EqualFold(resp, "yes") {
			fmt.Fprintln(os.Stderr, "aborted")
			os.Exit(1)
		}
	}
	overrides := restoreOverrides{
		configDir: *cfgDir,
		stateDir:  *stateDir,
		logDir:    *logDir,
		force:     *force,
	}
	// Cross-platform path translation: when the backup's platform
	// differs from the current platform, retarget any unset path to
	// the current platform's defaults. Without this, restoring a
	// Windows backup on Linux would extract into literal directory
	// names containing colons and backslashes — Linux accepts the
	// bytes, the daemon never reads them, and the operator gets a
	// "successful" restore that did nothing useful.
	preview, err := peekManifest(*in, passphrase)
	if err != nil {
		fatalf("read backup manifest: %v", err)
	}
	overrides = crossPlatformPathOverrides(preview, overrides)

	m, err := restoreBackup(*in, passphrase, *dryRun, overrides)
	if err != nil {
		fatalf("restore: %v", err)
	}
	if *dryRun {
		return
	}
	fmt.Printf("restore complete from backup created at %s UTC by %s/%s on %s\n",
		m.CreatedAtUTC.Format("2006-01-02 15:04:05"), m.Platform, m.Arch, m.HostID)

	// Post-restore identity rebind: rewrite path-shaped config fields
	// for the current platform, re-issue the server cert under the
	// LOCAL hostname (so peers verify it cleanly), drop self-pointing
	// realm.peers entries, add the backup source as a peer (so a
	// cross-swap auto-re-peers), and clear server.local_id (so the
	// daemon stamps events with the local hostname). Best-effort: on
	// any failure here a warning prints; the operator can fix
	// manually before `simplesiem start`.
	dest := resolveRestoreTargets(m, overrides)
	applyPostRestoreRebind(filepath.Join(dest.configDir, "config.json"), m, dest)

	fmt.Println("next steps:")
	fmt.Println("  1. sudo simplesiem fix    # repair service registration if the OS changed")
	fmt.Println("  2. sudo simplesiem start")
	fmt.Println("  3. simplesiem status      # confirm mode + realm + storage")
}

// resolveBackupPassphrase returns the cleartext passphrase to use when
// creating a backup. Empty + --no-encrypt yields ""; otherwise an
// empty passphrase is rejected so an operator never accidentally
// produces a plaintext backup with private keys inside.
func resolveBackupPassphrase(pass, passFile string, noEncrypt bool) (string, error) {
	if noEncrypt {
		if pass != "" || passFile != "" {
			return "", fmt.Errorf("--no-encrypt cannot be combined with --passphrase or --passphrase-file")
		}
		return "", nil
	}
	if passFile != "" {
		b, err := os.ReadFile(passFile)
		if err != nil {
			return "", fmt.Errorf("read passphrase file: %w", err)
		}
		pass = strings.TrimSpace(string(b))
	}
	if pass == "" {
		return "", fmt.Errorf("encryption is required by default; supply --passphrase, --passphrase-file, or --no-encrypt")
	}
	return pass, nil
}

// pathsOnSameVolume returns true when two filesystem paths are
// hosted by the same underlying device. Cross-platform via gopsutil's
// disk.Partitions, which exposes mount-point + device tuples on
// Linux/macOS/Windows uniformly. The returned error is non-nil when
// the lookup could not be completed (caller treats that as "don't
// know — let the operation proceed" rather than blocking).
func pathsOnSameVolume(a, b string) (bool, error) {
	parts, err := disk.Partitions(true)
	if err != nil {
		return false, err
	}
	dev := func(path string) string {
		// Walk up the directory tree until we find a path that exists.
		// Then pick the partition with the longest matching mountpoint
		// — that's the most specific mount, i.e. the actual volume
		// hosting this path.
		for {
			if _, err := os.Stat(path); err == nil {
				break
			}
			parent := parentDir(path)
			if parent == path {
				return ""
			}
			path = parent
		}
		best := ""
		bestLen := -1
		for _, p := range parts {
			if strings.HasPrefix(path, p.Mountpoint) && len(p.Mountpoint) > bestLen {
				best = p.Device
				bestLen = len(p.Mountpoint)
			}
		}
		return best
	}
	devA := dev(a)
	devB := dev(b)
	if devA == "" || devB == "" {
		return false, fmt.Errorf("could not resolve volume for %q or %q", a, b)
	}
	return devA == devB, nil
}
